### PR TITLE
Quiet mode should not ask user if he wants to upload the results. 

### PR DESCRIPTION
**Pull request by guillermo**
```
gem test --quiet rubygems-test
gem test -q some_other_gem
```

should not ask user if he wants to upload results. So it is easy to batch test some gems, as:

```
rvm gem test -q rubygems-test
```

### CODE REVIEW

**Comment by erikh** [comment]
This looks great; I'll try and merge it later tonight or tomorrow.

**Comment by erikh** [comment]
Actually; there's a problem here:

 -q should also install development dependencies. Can you adjust this code to accomodate that?

**Comment by guillermo** [comment]
That is fixed in that commit.

**Comment by erikh** [comment]
Merged this, will show up when I push. Thanks for your help!

**Pull request merged**
